language: php

php:
  - 5.3
  - 5.4

before_install:
  - sh -e .travis/scripts/apt-get.sh
  - sh -e .travis/scripts/apache2-vhost.sh
  - sh -e .travis/scripts/apache2-configure.sh

before_script:
  - pyrus channel-discover pear.phpunit.de
  - pyrus install --force phpunit/DbUnit
  - pyrus install -f pear/PHP_CodeSniffer
  - phpenv rehash
  - cd ../ && git clone git://github.com/joomla/joomla-platform.git && cd BabDev-Libraries

script:
  - ant clean
  - phpunit --configuration phpunit.travis.xml
  - ant travis-phpcs
