# Forces new Travis-CI Infrastructure
sudo: false

language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

install:
  - composer install

script:
  - ant clean
  - ./vendor/bin/phpunit --configuration phpunit.travis.xml --coverage-clover=coverage.clover
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then ./vendor/bin/phpcs --report=full --extensions=php -p --standard=build/phpcs/Joomla/ruleset.xml src/; fi"
