language: php

php:
  - 5.3
  - 5.4

before_install:
  - composer self-update
  - sh -e .travis/scripts/apt-get.sh
  - sh -e .travis/scripts/apache2-vhost.sh
  - sh -e .travis/scripts/apache2-configure.sh

before_script:
  - composer update --dev

script:
  - ant clean
  - ./vendor/phpunit/phpunit/phpunit --configuration phpunit.travis.xml
  - ant travis-phpcs
