# Forces new Travis-CI Infrastructure
sudo: false

language: php

env:
  global:
    - USE_SCRUTINIZER="no"

matrix:
  include:
    - php: 7.2
      env: PHPUNIT_FLAGS="--coverage-clover=coverage.clover" USE_SCRUTINIZER="yes"
    - php: 7.3
    - php: 7.4snapshot
    - php: nightly
  allow_failures:
    - php: 7.4snapshot
    - php: nightly

before_install:
  - composer self-update

install:
  - composer install

script:
  - vendor/bin/phpunit --configuration phpunit.travis.xml $PHPUNIT_FLAGS
  - if [ "$USE_SCRUTINIZER" == "yes" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;
  - if [ "$USE_SCRUTINIZER" == "yes" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;
