# Forces new Travis-CI Infrastructure
sudo: false

language: php

env:
  global:
    - RUN_PHPCS="no"
    - USE_MINIMUM="no"
    - USE_SCRUTINIZER="no"

matrix:
  include:
    - php: 5.3.10
      env: USE_MINIMUM="yes"
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: 5.6
      env: PHPUNIT_FLAGS="--coverage-clover=coverage.clover" RUN_PHPCS="yes" USE_SCRUTINIZER="yes"
    - php: 7.0


before_install:
  - composer self-update

install:
  - if [ "$USE_MINIMUM == "yes"]; then composer update --prefer-lowest; fi;
  - if [ "$USE_MINIMUM == "no"]; then composer install; fi;

script:
  - ant clean
  - vendor/bin/phpunit --configuration phpunit.travis.xml $PHPUNIT_FLAGS
  - if [ "$USE_SCRUTINIZER" == "yes" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;
  - if [ "$USE_SCRUTINIZER" == "yes" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;
  - if [ "$RUN_PHPCS" == "yes" ]; then vendor/bin/phpcs --report=full --extensions=php -p --standard=build/phpcs/Joomla/ruleset.xml src/; fi
